# Exercise 17.1 by Michael Gergen
## (Books Database) In an IPython session, perform each of the following tasks on the books database from Section 17.2:
### a) Select all authors’ last names from the authors table in descending order.

In [32]:
import sqlite3
import pandas as pd

connection = sqlite3.connect("books.db")

In [33]:
pd.read_sql("""SELECT *
FROM authors
ORDER BY last DESC, first DESC
""", connection, index_col=['id'])

        first    last
id
5   Alexander    Wald
4         Dan   Quirk
1        Paul  Deitel
2      Harvey  Deitel
3       Abbey  Deitel

### b) Select all book titles from the titles table in ascending order.

In [34]:
pd.read_sql("""SELECT title FROM titles
ORDER BY title ASC""", connection)

                              title
0         Android 6 for Programmers
1            Android How to Program
2                  C How to Program
3                C++ How to Program
4     Internet & WWW How to Program
5     Intro to Python for CS and DS
6               Java How to Program
7  Visual Basic 2012 How to Program
8          Visual C# How to Program
9         Visual C++ How to Program

### c) Use an INNER JOIN to select all the books for a specific author. Include the title, copyright year and ISBN. Order the information alphabetically by title.

In [35]:
# we do not need the ID stuff because they do not share any similar names.
# use the WHERE for a specific author
pd.read_sql("""SELECT first, last, title, copyright, isbn
FROM authors
INNER JOIN titles
WHERE last = 'Quirk'""", connection)

#ORDER BY last, first, title""",connection)

  first   last                             title copyright        isbn
0   Dan  Quirk     Intro to Python for CS and DS      2020  0135404673
1   Dan  Quirk     Internet & WWW How to Program      2012  0132151006
2   Dan  Quirk               Java How to Program      2018  0134743350
3   Dan  Quirk                  C How to Program      2016  0133976890
4   Dan  Quirk  Visual Basic 2012 How to Program      2014  0133406954
5   Dan  Quirk          Visual C# How to Program      2017  0134601548
6   Dan  Quirk         Visual C++ How to Program      2008  0136151574
7   Dan  Quirk                C++ How to Program      2017  0134448235
8   Dan  Quirk            Android How to Program      2017  0134444302
9   Dan  Quirk         Android 6 for Programmers      2016  0134289366

### d) Insert a new author into the authors table.

In [36]:
cursor = connection.cursor()
cursor = cursor.execute("""INSERT INTO authors (first, last)
VALUES ('Walter', 'White')""")

In [37]:
# check insertion
pd.read_sql("SELECT * FROM authors ORDER BY last DESC, first DESC", connection)

   id      first    last
0   6     Walter   White
1   5  Alexander    Wald
2   4        Dan   Quirk
3   1       Paul  Deitel
4   2     Harvey  Deitel
5   3      Abbey  Deitel

### e) Insert a new title for an author. Remember that the book must have an entry in the author_ISBN table and an entry in the titles table.

In [38]:
#in order to link these to the author in the structure of the table, we have to make sure that the IDs and ISBNs match each other in their respective fields.

cursor = cursor.execute("""INSERT INTO author_ISBN (id, isbn)
VALUES ('6','0123456789')""")
cursor = cursor.execute("""
INSERT INTO titles (isbn, title, edition, copyright)
VALUES ('0123456789', 'Test Title', 'Test Edition', 'Test Copyright')""")

In [39]:
pd.read_sql("""SELECT first, last, title, copyright, isbn
FROM authors
INNER JOIN titles
WHERE last = 'White'""", connection)

,first,last,title,copyright,isbn
0,Walter,White,Intro to Python for CS and DS,2020,0135404673
1,Walter,White,Internet & WWW How to Program,2012,0132151006
2,Walter,White,Java How to Program,2018,0134743350
3,Walter,White,C How to Program,2016,0133976890
4,Walter,White,Visual Basic 2012 How to Program,2014,0133406954
5,Walter,White,Visual C# How to Program,2017,0134601548
6,Walter,White,Visual C++ How to Program,2008,0136151574
7,Walter,White,C++ How to Program,2017,0134448235
8,Walter,White,Android How to Program,2017,0134444302
9,Walter,White,Android 6 for Programmers,2016,0134289366
10,Walter,White,Test Title,Test Copyright,0123456789

In [40]:
connection.close()